kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  namespace: openshift
  name: hello-openshift
  annotations:
    release.openshift.io/delete: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    include.release.openshift.io/single-node-production-edge: "true"
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      importPolicy:
        scheduled: true
      from:
        kind: DockerImage
        name: quay.io/openshift/origin-hello-openshift:latest
